### ISSUE TITLE
package-lock modified, correct package not-found

### ISSUE THREAD

**Issue by codejedi365** [angelogiuseppe/force-resolutions#1]
I don't understand how this project is working under the hood. I moved to this package because `npm-force-resolutions` hinders a production install if it fixes devDependency issues.  I also like the new logging information!  However, it makes changes to `package-lock.json` for resolution but it never installs the latest package.

```json5
// My package.json
{
  // ...
  "devDependencies": {
      "eslint-plugin-mdx": "^1.16.0"
  },
  "resolutions": {
      "trim": "^1.0.1"
  }
  // ...
}
```

```json5
// package-lock.json
{
  // ...
  "packages": {
    // ...
    "node_modules/remark-parse": {
        "version": "8.0.3",
        "resolved": "https://registry.npmjs.org/remark-parse/-/remark-parse-8.0.3.tgz",
        "integrity": "sha512-E1K9+QLGgggHxCQtLt++uXltxEprmWzNfg+MxpfHsZlrddKzZ/hZyWHDbK3/Ap8HJQqYJRXP+jHczdL6q6i85Q==",
        "dev": true,
        "dependencies": {
          "ccount": "^1.0.0",
          "collapse-white-space": "^1.0.2",
          "is-alphabetical": "^1.0.0",
          "is-decimal": "^1.0.0",
          "is-whitespace-character": "^1.0.0",
          "is-word-character": "^1.0.0",
          "markdown-escapes": "^1.0.0",
          "parse-entities": "^2.0.0",
          "repeat-string": "^1.5.4",
          "state-toggle": "^1.0.0",
          "trim": "^1.0.1",
          "trim-trailing-lines": "^1.0.0",
          "unherit": "^1.0.4",
          "unist-util-remove-position": "^2.0.0",
          "vfile-location": "^3.0.0",
          "xtend": "^4.0.1"
        },
        "funding": {
          "type": "opencollective",
          "url": "https://opencollective.com/unified"
        }
      },
    // ...
  },
  "dependencies": {
    // ...
    "remark-parse": {
        "version": "8.0.3",
        "resolved": "https://registry.npmjs.org/remark-parse/-/remark-parse-8.0.3.tgz",
        "integrity": "sha512-E1K9+QLGgggHxCQtLt++uXltxEprmWzNfg+MxpfHsZlrddKzZ/hZyWHDbK3/Ap8HJQqYJRXP+jHczdL6q6i85Q==",
        "dev": true,
        "requires": {
          "ccount": "^1.0.0",
          "collapse-white-space": "^1.0.2",
          "is-alphabetical": "^1.0.0",
          "is-decimal": "^1.0.0",
          "is-whitespace-character": "^1.0.0",
          "is-word-character": "^1.0.0",
          "markdown-escapes": "^1.0.0",
          "parse-entities": "^2.0.0",
          "repeat-string": "^1.5.4",
          "state-toggle": "^1.0.0",
          "trim": "^1.0.1",
          "trim-trailing-lines": "^1.0.0",
          "unherit": "^1.0.4",
          "unist-util-remove-position": "^2.0.0",
          "vfile-location": "^3.0.0",
          "xtend": "^4.0.1"
        },
        "dependencies": {
          "trim": {
            "version": "^1.0.1"
          }
        }
      },
    // ...
    "trim": {
        "version": "https://registry.npmjs.org/trim/-/trim-0.0.1.tgz",
        "integrity": "sha1-WFhUf2spB1fulczMZm+1AITEYN0=",
        "dev": true
      },
    // ...
  }
}
```

The `package-lock.json` is updated to resolve to the `1.0.1` version in all places except for the last `tar.gz` file.

Then if you peek into the `node_modules/trim/package.json` the version listed is still `v0.0.1`.  This means to me that it was never installed.  I though you might be using path shims or something and looked into `node_modules/remark-parse` for a possible `node_modules` folder with the correctly downloaded trim version and there is no folder there either.

Furthermore, if I run `npm audit` it still shows that `trim@0.0.1` has the vulnerability that I'm trying to override.  

I performed this similar validation on `npm-force-resolutions`.  My results were: Run npm install, on preinstall the package-lock was modified and on the second `npm install`, the correct trim was installed at the top level.  Now I run install or ci and neither actually install the correct trim package.

This is the result I get when I try to verify what is installed.
```log
$> npm ls trim
eslint-plugin-testcafe-community@1.2.3
└─┬ eslint-plugin-mdx@1.16.0
  └─┬ eslint-mdx@1.16.0
    └─┬ remark-parse@8.0.3
      └── trim@0.0.1 invalid: "^1.0.1" from node_modules/remark-parse
```

How is this supposed to work?

**Comment by angelogiuseppe** [comment]
Hi @codejedi365 , I'll try to replicate today, and see if I can come up with a solution, if I can't replicate, I'll send you a message to get in touch and investigate the issue more deeply

**Comment by angelogiuseppe** [comment]
Apologies for taking some days to answer, I didn't see the notification 👍

**Comment by jpambrun** [comment]
I have the same issue. As it is, force-resolution doesn't appear to be doing anything to actually force a version to be installed.

**Comment by angelogiuseppe** [comment]
A new version is been released recently check the readme to join the discord server if issues are still happening
Here is the new version: https://www.npmjs.com/package/force-resolutions?activeTab=readme
