### ISSUE TITLE
Only partial resolution of versions

### ISSUE THREAD

**Issue by hajnyon** [angelogiuseppe/force-resolutions#2]
Hi, thanks for the effort to provide alternative to npm-force-resolution! I tried to use this package but came across some difficulties. It seems to me it doesn't resolve all versions correctly. I managed to filter this to a minimal setup described below. I am not able to tell if this is a problem with this package or package I'm trying to lock version to.

## Steps to reproduce

package.json
```json
"resolutions": {
    "aurelia-loader-webpack": "2.1.0"
}
```

```bash
npm init -y
npm i -D aurelia-webpack-plugin@4
npx force-resolutions
```

After this, package-lock.json has only few versions updated and `npm ls aurelia-loader-webpack` outputs `2.2.4` as well:

- `packages.node_modules/aurelia-loader-webpack.version` = `2.2.4` - wrong
- `packages.node_modules/aurelia-webpack-plugin.dependencies.aurelia-loader-webpack` = `2.1.0` - correct
- `dependencies.aurelia-loader-webpack.version` = `2.2.4` - wrong

I hope I described it sufficiently. I can add repository with this example if needed.

**Comment by marchage** [comment]
Hi,

Yeah, I'm having the same problem. 

I'm trying to fix it, but package-lock's aren't my favorite subject so to speak, + it is not so easy as setting a field to a number I guess (*I hope I'm wrong on that one*). 

I've changed the excellent (👍 /tnx) code a bit to output some `keyPaths`, `resolutions` and `resolutions[resolution]s`, my test case was chokidar 2 and getting it to 3. (I've *had* it with that notification, it's  😱 ) (in reality it seems to show abandonment perhaps, des-interest in some cases, or any reason not to upgrade actually/I don't blame the Chokidars-guy, I think... 🤔 ... did he place that message? But never mind that now)

It seems that there is something going on in the *`findKeyPaths`* I think. Part of what I get as ouput is is:
```
[etc...]
┌resolution: packages.node_modules/[some_dep_x].dependencies.chokidar
├─      - packages.node_modules/[some_dep_x].dependencies.chokidar gave keyPaths:
├──     - 
└no modifications packages.node_modules/[some_dep_x].dependencies.chokidar
packages.node_modules/[some_dep_x].dependencies.chokidar => 3.5.2
┌resolution: chokidar
├─      - chokidar gave keyPaths:
[etc...]
├──     - packages.node_modules/[some_dep_x].dependencies.chokidar
[etc...]
├──     - dependencies.chokidar
├──     - dependencies.[some_dep_x].requires.chokidar
├──     - dependencies.[some_dep_x].dependencies.chokidar
[etc...]
```
(between `[` <-> `]` = removed) 
As you can see from the first line I am trying to target the following key in my package-lock.json `"node_modules/[some_dep_x]/node_modules/chokidar"`, it's part of the "packages"-key, but paths isn't showing it. I have yet to find out if I can just overwrite values of it with simple npm view results, so perhaps I'm going about this al wrong!, but I *do* see a url in "resolved"-field already present, so my guess was: I can just overwrite them (*I hope I'm right on that one*).

It seems the closest it's gotten is `packages.node_modules/[some_dep_x].dependencies.chokidar`. I see some things going on with `predicate` and `discoveredCyclicObjects`... my best guess atm is: its something there.

Regards/Best wishes 🥂

**Comment by marchage** [comment]
(writing it down I see I made a mistake there...)(one moment)

**Comment by marchage** [comment]
(huh?! it's not wrong?!) (like I said, not super easy)

**Comment by hajnyon** [comment]
Hi, I'm a little confused as few notifications were delivered to my email, but there are no responses here. So I guess you removed the answers?

However, I've resolved my issue differently (by fixing all issues that blocked updating the package version). Moreover, on the second look, altering of `package-lock.json` doesn't seem as good and more as a "hacky" solution. Feel free to close this issue if you are not going to look in to it more.

**Comment by angelogiuseppe** [comment]
A new version is been released recently check the readme to join the discord server if issues are still happening
Here is the new version: https://www.npmjs.com/package/force-resolutions?activeTab=readme
