### ISSUE TITLE
Module name parser incorrectly splitting on package names with '.'

### ISSUE THREAD

**Issue by rebyul** [angelogiuseppe/force-resolutions#3]
Problem: npx force-resolution fails to execute as it splits the package name into a nested json node

To reproduce:

1. npm install {package name with . in the name} (e.g. twin.macro)
2. Add preinstall script: npx force-resolution
3. run npm i

Console output:
```
> npx force-resolutions

npx: installed 1 in 0.709s
Applying forced resolutions
resolve => 1.21.0
Finished applying forced resolutions
⸨ ░░░░░░░░░░░░░░░░░⸩ ⠋ loadIdealTree:loadAllDepsIntoIdealTree: sill install loadIdealTree
          NPM is trying to retrieve package "twin" with version "undefined"!
          Package location: undefined
          Package parse error: undefined
npm ERR! Cannot read property 'match' of undefined
```

**Comment by angelogiuseppe** [comment]
A new version is been released recently check the readme to join the discord server if issues are still happening
Here is the new version: https://www.npmjs.com/package/force-resolutions?activeTab=readme
