### ISSUE TITLE
`npm ci` updates `package-lock.json`

### ISSUE THREAD

**Issue by niknbr** [angelogiuseppe/force-resolutions#4]
Hi, Thanks for this package. 🙂 

There seems to be an issue when we run `npm ci`. It is updating the `package-lock.json`, even though the resolutions were applied already during the `npm install`.

To reproduce

- Clone https://github.com/niknbr/test-force-resolutions
- Run `npm install` to update the `package-lock.json` with `trim` package force resolved to `0.0.3`. (this doesn't update the requires field of `trim` under `remark-parse` to `0.0.3` though 🤔 )
  
<img width="888" alt="image" src="https://user-images.githubusercontent.com/7285903/159261134-4e80dffc-cc8e-4367-a760-5ed003a80d43.png">

- Commit the `package-lock.json`
- Run `npm ci`. This updates the `package-lock.json` as follows

<img width="815" alt="image" src="https://user-images.githubusercontent.com/7285903/159261856-6a1eb7a6-027b-46e7-9025-57609db35e23.png">

I believe, the expectation would be that `npm ci` would not update `package-lock.json` and even if it does the changes must not be different from `npm install` ?

**Comment by angelogiuseppe** [comment]
The script removes certain fields that are then re-generated. In this case the resolved and integrity fields are deleted as they are unique to a version, as we update the version they have to change, but we don't know their values, but npm does, hence we run npm install or npm ci and those fields will be added with their corresponding updated values. So, this behavior is normal.

A new version is been released recently check the readme to join the discord server if issues are still happening
Here is the new version: https://www.npmjs.com/package/force-resolutions?activeTab=readme
